# -*- coding: utf-8 -*-
"""Bienvenue dans Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""loading dataset"""

customers = pd.read_csv('dataset.csv')
customers.head()

"""To see the descriptive statistics for each variable use describe()"""

customers.describe()

sns.countplot(x='Genre', data=customers)
plt.title('Distribution of Gender')

"""if you want to observe and create a histogram of ages"""

customers.hist('Age', bins=35)
plt.title('Distribution of Age')
plt.xlabel('Age')

"""You can add detail to this by overlaying two histograms, creating one age histogram for each gender"""

plt.hist('Age', data=customers[customers['Genre'] == 'Male'], alpha=0.5, label='Male')
plt.hist('Age', data=customers[customers['Genre'] == 'Female'], alpha=0.5, label='Female')
plt.title('Distribution of Age by Gender');
plt.xlabel('Age')
plt.legend()

"""You can add detail about coustomer income"""

customers.hist('Annual Income (k$)')
plt.title('Annual Income Distribution in Thousands of Dollars')
plt.xlabel('Thousands of Dollars')

"""Histogram of income by gender"""

plt.hist('Annual Income (k$)', data=customers[customers['Genre'] == 'Male'], alpha=0.5, label='Male')
plt.hist('Annual Income (k$)', data=customers[customers['Genre'] == 'Female'], alpha=0.5, label='Female')
plt.title('Distribution of Income by Gender')
plt.xlabel('Income (Thousands of Dollars)')
plt.legend()

"""Spending score : 
Create data sets by gender
"""

male_customers = customers[customers['Genre'] == 'Male']
female_customers = customers[customers['Genre'] == 'Female']

"""the average spending score for men and women"""

print(male_customers['Spending Score (1-100)'].mean())
print(female_customers['Spending Score (1-100)'].mean())

"""For more understanding of data :"""

sns.scatterplot('Age', 'Annual Income (k$)', hue='Genre', data=customers)
plt.title('Age and Income by Gender')

"""to find any possible correlations in data just call"""

sns.heatmap(customers.corr(), annot=True)

"""age and spending score by gender scatter"""

sns.scatterplot('Age', 'Spending Score (1-100)', hue='Genre', data=customers)
plt.title('Age to Spending Score, Colored by Gender')

"""you can use specific gender to study the correlaton : (female as an example)"""

sns.heatmap(female_customers.corr(), annot=True)
plt.title('Correlation Heatmap - Female')

"""lets now show the correlation between age and spending score for women"""

sns.lmplot('Age', 'Spending Score (1-100)', data=female_customers)
plt.title('Age to Spending Score, Female Only')

"""income to spending score colored by gender"""

sns.scatterplot('Annual Income (k$)', 'Spending Score (1-100)', hue='Genre', data=customers)
plt.title('Annual Income to Spending Score, Colored by Gender')